version: 1.0
dataset_name: spotify_tracks
description: Schema for Spotify dataset (1960-2019)

columns:
  track: string
  artist: string
  uri: string
  danceability: float
  energy: float
  key: int
  loudness: float
  mode: int
  speechiness: float
  acousticness: float
  instrumentalness: float
  liveness: float
  valence: float
  tempo: float
  duration_ms: int
  time_signature: int
  chorus_hit: float
  sections: int
  target: int


numerical_features:
  - danceability
  - energy
  - loudness
  - speechiness
  - acousticness
  - instrumentalness
  - liveness
  - valence
  - tempo
  - duration_ms
  - chorus_hit
  - sections

categorical_features:
  - key
  - mode
  - time_signature

columns_to_drop:
  - track
  - artist
  - uri

target_column:
  - target

rules:
  required_columns:
    - track
    - artist
    - danceability
    - energy
    - loudness
    - tempo
    - duration_ms
    - target
  
  numerical_ranges:
    danceability: [0.0, 1.0]
    energy: [0.0, 1.0]
    speechiness: [0.0, 1.0]
    acousticness: [0.0, 1.0]
    instrumentalness: [0.0, 1.0]
    liveness: [0.0, 1.0]
    valence: [0.0, 1.0]
    tempo: [0, 250]
    duration_ms: [10000, 1000000]
    loudness: [-60, 5]

  categorical_values:
    key: [0,1,2,3,4,5,6,7,8,9,10,11]
    mode: [0,1]
    time_signature: [3,4,5]
    target: [0,1]
